import os
from datetime import datetime, timezone
from config import Config


def send_monthly_report(report_md: str, stats: dict) -> dict:
    """
    Send monthly DevRel report via SendGrid.
    Returns dict with success status and message.
    """
    if not Config.SENDGRID_API_KEY:
        return {'success': False, 'message': 'SendGrid API key not configured'}

    if not Config.ADMIN_EMAIL:
        return {'success': False, 'message': 'Admin email not configured'}

    try:
        import sendgrid
        from sendgrid.helpers.mail import (
            Mail, Attachment, FileContent, FileName,
            FileType, Disposition, ContentId
        )
        import base64

        now = datetime.now(timezone.utc)
        month_year = now.strftime('%B %Y')
        subject = f"Orbit Monthly DevRel Report — {month_year}"

        # Build inline HTML summary
        html_summary = f"""
        <div style="font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: #0a0a0a; padding: 24px; border-radius: 12px; margin-bottom: 24px;">
                <h1 style="color: #76B900; font-size: 24px; margin: 0 0 4px;">Orbit.</h1>
                <p style="color: #888; font-size: 12px; margin: 0; font-family: monospace;">NVIDIA ISV Intelligence Platform</p>
            </div>

            <h2 style="color: #111; font-size: 20px;">Monthly DevRel Report — {month_year}</h2>
            <p style="color: #555; font-size: 14px;">Here is your automated monthly summary of ISV adoption activity on Orbit.</p>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 24px 0;">
                <div style="background: #f8f8f8; padding: 16px; border-radius: 8px; border-left: 3px solid #76B900;">
                    <div style="font-size: 28px; font-weight: 700; color: #76B900;">{stats.get('total_sessions', 0)}</div>
                    <div style="font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.08em;">Total Sessions</div>
                </div>
                <div style="background: #f8f8f8; padding: 16px; border-radius: 8px; border-left: 3px solid #00C4CC;">
                    <div style="font-size: 28px; font-weight: 700; color: #00C4CC;">{stats.get('completions', 0)}</div>
                    <div style="font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.08em;">Completions</div>
                </div>
                <div style="background: #f8f8f8; padding: 16px; border-radius: 8px; border-left: 3px solid #6B3FA0;">
                    <div style="font-size: 28px; font-weight: 700; color: #6B3FA0;">{stats.get('completion_rate', 0)}%</div>
                    <div style="font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.08em;">Completion Rate</div>
                </div>
                <div style="background: #f8f8f8; padding: 16px; border-radius: 8px; border-left: 3px solid #f59e0b;">
                    <div style="font-size: 28px; font-weight: 700; color: #f59e0b;">{stats.get('isv_sessions', 0)}</div>
                    <div style="font-size: 12px; color: #888; text-transform: uppercase; letter-spacing: 0.08em;">ISV Sessions</div>
                </div>
            </div>

            <h3 style="color: #111; font-size: 16px; margin-top: 24px;">Trending Topics</h3>
            <ul style="color: #555; font-size: 14px; padding-left: 20px;">
                {''.join([f"<li><strong>{t['topic']}</strong> ({t['count']} mentions) — {t['suggestion']}</li>" for t in stats.get('trending_topics', [])[:4]])}
            </ul>

            <h3 style="color: #111; font-size: 16px; margin-top: 24px;">Format Preferences</h3>
            <ul style="color: #555; font-size: 14px; padding-left: 20px;">
                {''.join([f"<li>{f['format']}: {f['percentage']}%</li>" for f in stats.get('format_distribution', [])])}
            </ul>

            <div style="margin-top: 32px; padding: 16px; background: #f8f8f8; border-radius: 8px;">
                <p style="color: #888; font-size: 12px; margin: 0;">
                    Full report attached as <code>orbit-monthly-report.md</code><br>
                    Generated by Orbit — NVIDIA ISV Intelligence Platform
                </p>
            </div>
        </div>
        """

        # Attach the markdown report
        encoded = base64.b64encode(report_md.encode('utf-8')).decode()

        message = Mail(
            from_email=Config.SENDGRID_FROM_EMAIL,
            to_emails=Config.ADMIN_EMAIL,
            subject=subject,
            html_content=html_summary
        )

        attachment = Attachment(
            FileContent(encoded),
            FileName(f'orbit-monthly-report-{now.strftime("%Y-%m")}.md'),
            FileType('text/markdown'),
            Disposition('attachment'),
            ContentId('MonthlyReport')
        )
        message.attachment = attachment

        sg = sendgrid.SendGridAPIClient(api_key=Config.SENDGRID_API_KEY)
        response = sg.send(message)

        if response.status_code in [200, 202]:
            return {
                'success': True,
                'message': f'Report sent to {Config.ADMIN_EMAIL}',
                'status_code': response.status_code
            }
        else:
            return {
                'success': False,
                'message': f'SendGrid error: {response.status_code}',
                'status_code': response.status_code
            }

    except ImportError:
        return {'success': False, 'message': 'SendGrid package not installed. Run: pip install sendgrid'}
    except Exception as e:
        return {'success': False, 'message': str(e)}


def should_send_monthly_report() -> bool:
    """
    Check if it's the last day of the month and report hasn't been sent yet.
    """
    import calendar
    now = datetime.now(timezone.utc)
    last_day = calendar.monthrange(now.year, now.month)[1]

    # Check state file
    state_file = os.path.join('data', 'email_state.json')
    try:
        import json
        with open(state_file, 'r') as f:
            state = json.load(f)
        last_sent = state.get('last_report_sent', '')
        current_month = now.strftime('%Y-%m')
        if last_sent.startswith(current_month):
            return False
    except (FileNotFoundError, Exception):
        pass

    return now.day == last_day


def mark_report_sent():
    """Mark that the monthly report was sent."""
    import json
    state_file = os.path.join('data', 'email_state.json')
    os.makedirs('data', exist_ok=True)
    now = datetime.now(timezone.utc)
    with open(state_file, 'w') as f:
        json.dump({'last_report_sent': now.isoformat()}, f)